#!/usr/bin/env python

from pyScore.util.script_helpers import *
from pyScore.MusicXML.validate import validate
import pyScore.Guido.convert

import sys

def callback(options, input_file, output_file):
   if options.dtd:
      validate(output_file)

convert(
   [pyScore.Guido.convert],
   Format("Guido", "gmn", "guido_file"),
   Format("GIF", "gif", "image"),
   extra_args=[
	(("-x", "--width"), {'action': 'store_true', 'dest': 'width', 'help': 'Width of the GIF file.'}),
	(("-y", "--height"), {'action': 'store_true', 'dest': 'height', 'help': 'Height of the GIF file.'}),
	(("-z", "--zoom"), {'action': 'store_true', 'dest': 'zoom', 'help': 'Magnification.'}),
	],
   extra_dict=["width", "height", "zoom"])
