#!/usr/bin/env python

from pyScore.util.script_helpers import *
from pyScore.MusicXML.validate import validate
import pyScore.Guido.convert
import pyScore.MusicXML.convert
import pyScore.MIDI.convert

import sys

convert(
   [pyScore.Guido.convert, pyScore.MusicXML.convert, pyScore.MIDI.convert],
   Format("Guido", "gmn", "Guido_file"),
   Format("MIDI", "mid", "MIDI_file"))
