#!/usr/bin/env python

from pyScore.config import config
import pyScore.Guido.convert
from pyScore.MusicXML.validate import validate
from pyScore.util.script_helpers import *

import sys

config.add_option("-x", "--width", action="store", help="[guido] Width of the GIF file.")
config.add_option("-y", "--height", action="store", help="[guido] Height of the GIF file.")
config.add_option("-z", "--zoom", action="store", help="[guido] Zoom of the GIF file.")

convert(
   [pyScore.Guido.convert],
   Format("Guido", "gmn", "Guido_file"),
   Format("GIF", "gif", "Guido_image"))
