#!/usr/bin/env python

from pyScore.util.script_helpers import *
from pyScore.MusicXML.validate import validate
import pyScore.Guido.convert
import pyScore.MusicXML.convert

import sys

convert(
   [pyScore.Guido.convert, pyScore.MusicXML.convert],
   Format("MusicXML", "xml", "MusicXML_file"),
   Format("Guido", "gmn", "Guido_file"))
