#!/usr/bin/env python

from pyScore.util.script_helpers import *
from pyScore.MusicXML.validate import validate
import pyScore.Guido.convert
import pyScore.MusicXML.convert

import sys

def callback(options, input_file, output_file):
   if options.dtd:
      validate(input_file)

convert(
   [pyScore.Guido.convert, pyScore.MusicXML.convert],
   Format("MusicXML", "xml", "musicxml_file"),
   Format("Guido", "gmn", "guido_file"),
   extra_args=[(("-d", "--dtd"), {'action': 'store_true', 'dest': 'dtd', 'help': 'Validate against the MusicXML DTD'})],
   callback=callback)
