#!/usr/bin/env python

from pyScore.util.script_helpers import *
from pyScore.MusicXML.validate import validate
import pyScore.MusicXML.convert
import pyScore.Guido.convert

TEST_DIRECTORY = "tests"
tests = [
   ("Guido", Format("Guido", "gmn", "guido_file"),
    Format("Guido", "gmn", "guido_file")),
   ("Guido", Format("Guido", "gmn", "guido_file"),
    Format("MusicXML", "xml", "xml_file")),
]

def callback(input_file, output_file):
##    if output_file.endswith("xml"):
##       validate(output_file)
   pass

test([pyScore.Guido.convert, pyScore.MusicXML.convert],
     TEST_DIRECTORY, tests, groundtruth=True, callback=callback)
