#!/usr/bin/env python

import profile

from pyScore.util.script_helpers import *
from pyScore.MusicXML.validate import validate
import pyScore.MusicXML.convert
import pyScore.Guido.convert

from os.path import exists
import sys
i = 0
while exists("pyScore-%08d.profile" % i):
   i += 1
profile_file = "pyScore-%08d.profile" % i

TEST_DIRECTORY = "profile"
tests = [
   ("Guido", Format("Guido", "gmn", "guido_file"),
    Format("MusicXML", "xml", "musicxml_file")),
]

def callback(input_file, output_file):
##    if output_file.endswith("xml"):
##       validate(output_file)
   pass

profile.run("""test([pyScore.Guido.convert, pyScore.MusicXML.convert],
     TEST_DIRECTORY, tests, groundtruth=False, callback=callback)
""", profile_file)

import pstats
p = pstats.Stats(profile_file)
p.sort_stats('cumulative').print_stats(50)
p.sort_stats('time').print_stats(50)
p.sort_stats('time').print_callers(50)
