#!/usr/bin/env python

from pyScore.util.script_helpers import *
from pyScore.MusicXML.validate import validate
import pyScore.MusicXML.convert
import pyScore.Guido.convert

from os.path import isdir

TEST_DIRECTORY = "tests"
tests = [
   ("Guido", Format("Guido", "gmn", "guido_file"),
    Format("Guido", "gmn", "guido_file"),
    "Guido -> Guido",
    "This test exercises the Guido parser and grammar.  (MusicXML is uninvolved).  Some 'canonicalization' of the data is expected."),
   ("Guido", Format("Guido", "gmn", "guido_file"),
    Format("MusicXML", "xml", "musicxml_file"),
    "Guido -> MusicXML",
    "Converting all Guido Basic spec and some Guido Advanced spec to MusicXML."
   ),
   ("MusicXML",
    Format("MusicXML", "xml", "musicxml_file"),
    Format("Guido", "gmn", "guido_file"),
    "MusicXML -> Guido",
    "Preliminary support for converting MusicXML to Guido."
   )
   ]

def callback(input_file, output_file):
##    if output_file.endswith("xml"):
##       validate(output_file)
   pass

test([pyScore.Guido.convert, pyScore.MusicXML.convert],
     TEST_DIRECTORY, tests, groundtruth=True, callback=callback)
